-- MySQL Script generated by MySQL Workbench
-- Fri Oct 18 22:10:59 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema universidad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema universidad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `universidad` DEFAULT CHARACTER SET latin1 ;
USE `universidad` ;

-- -----------------------------------------------------
-- Table `universidad`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`carrera` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `universidad`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`materias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `creditos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `universidad`.`carrera_materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`carrera_materia` (
  `materia_id` INT(11) NOT NULL,
  `carrera_id` INT(11) NOT NULL,
  PRIMARY KEY (`materia_id`),
  INDEX `carrera_id_idx` (`carrera_id` ASC) VISIBLE,
  CONSTRAINT `carrera_id`
    FOREIGN KEY (`carrera_id`)
    REFERENCES `universidad`.`carrera` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `materia_id`
    FOREIGN KEY (`materia_id`)
    REFERENCES `universidad`.`materias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `universidad`.`estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`estudiantes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  `edad` VARCHAR(45) NOT NULL,
  `carrera_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `estudiante_carrera_id`
    FOREIGN KEY (`id`)
    REFERENCES `universidad`.`carrera` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `universidad`.`semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`semestre` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ciclo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `universidad`.`semestre_estudiante_materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`semestre_estudiante_materia` (
  `semestre_id` INT(11) NOT NULL,
  `estudiante_id` INT(11) NOT NULL,
  `materia_id` INT(11) NOT NULL,
  PRIMARY KEY (`semestre_id`),
  INDEX `estudiante_id_idx` (`estudiante_id` ASC) VISIBLE,
  INDEX `materia_id_idx` (`materia_id` ASC) VISIBLE,
  CONSTRAINT `estudiante_id`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `universidad`.`estudiantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sem_est_mat`
    FOREIGN KEY (`materia_id`)
    REFERENCES `universidad`.`materias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `semestre_id`
    FOREIGN KEY (`semestre_id`)
    REFERENCES `universidad`.`semestre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
